<?php

namespace Puzzle;

class Core
{
    const PUZZLE_VENDOR_SRC = 'vendor' . DIRECTORY_SEPARATOR . 'phink' . DIRECTORY_SEPARATOR . 'puzzle' . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR;
    const PUZZLE_VENDOR_LIB = Core::PUZZLE_VENDOR_SRC . 'lib' . DIRECTORY_SEPARATOR;
    const PUZZLE_VENDOR_APPS = Core::PUZZLE_VENDOR_SRC . 'apps' . DIRECTORY_SEPARATOR;
    const PUZZLEJS_VENDOR = Core::PUZZLE_VENDOR_LIB . 'js' . DIRECTORY_SEPARATOR;
    const PUZZLE_ROOT = SITE_ROOT . Core::PUZZLE_VENDOR_LIB;
    const PUZZLE_APPS_ROOT = SITE_ROOT . Core::PUZZLE_VENDOR_APPS;
    const PUZZLEJS_ROOT = SITE_ROOT . Core::PUZZLEJS_VENDOR;
}
